[package]
name = "stream_limiter"
version = "0.1.0"
edition = "2021"
authors = ["Aurélien Foucault <af@massa.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tempfile = "3.3.0"